import os
import json
import glob
import hashlib
from django.core.management.base import BaseCommand
from django.conf import settings
from django.utils.text import slugify
from chatbot.models import CollegeDetail, KnowledgeBaseQA

class Command(BaseCommand):
    help = 'Syncs college JSON files and question.txt into SQLite database'

    def handle(self, *args, **options):
        self.sync_colleges()
        # self.sync_qa_pairs()
        self.stdout.write(self.style.SUCCESS('Successfully synced all data!'))

    def sync_colleges(self):
        self.stdout.write('Syncing college details...')
        data_dir = settings.COLLEGE_DATA_DIR
        json_files = glob.glob(os.path.join(data_dir, '*_output.json'))
        
        for filepath in json_files:
            filename = os.path.basename(filepath)
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
                data = json.loads(content)
                file_hash = hashlib.sha256(content.encode('utf-8')).hexdigest()

            details = data.get('college_details', {})
            name = details.get('College Name', filename.replace('_output.json', '').title())
            slug = slugify(name)
            
            college, created = CollegeDetail.objects.update_or_create(
                slug=slug,
                defaults={
                    'name': name,
                    'data': data,
                    'file_hash': file_hash
                }
            )
            action = 'Created' if created else 'Updated'
            self.stdout.write(f'  - {action} college: {name}')

    def sync_qa_pairs(self):
        self.stdout.write('Syncing question-answer pairs from question.txt...')
        q_file = os.path.join(settings.BASE_DIR, 'data', 'question.txt')
        
        if not os.path.exists(q_file):
            self.stdout.write(self.style.WARNING(f'Question file not found: {q_file}'))
            return

        with open(q_file, 'r', encoding='utf-8') as f:
            lines = f.readlines()

        # Simple parser for question.txt
        # Assumes questions are lines that look like questions
        # Since question.txt is currently just a list of questions without answers,
        # and the user wants "Question and Answers", I will check if training_data.json exists 
        # which usually contains the QA pairs generated by the previous task.
        
        qa_json_path = os.path.join(settings.BASE_DIR, 'data', 'training_data.json')
        if os.path.exists(qa_json_path):
            self.stdout.write(f'Loading verified QA pairs from {qa_json_path}...')
            with open(qa_json_path, 'r', encoding='utf-8') as f:
                qa_data = json.load(f)
            
            # Performance optimization: Load all colleges into memory for matching
            all_colleges = list(CollegeDetail.objects.all())
            self.stdout.write(f'  - Loaded {len(all_colleges)} colleges for association.')
            
            new_qa_pairs = []
            for item in qa_data:
                q = item.get('instruction', '')
                a = item.get('response', '')
                if not q or not a:
                    continue
                
                # Associated with a college via pre-loaded list
                related_college = None
                q_lower = q.lower()
                for college in all_colleges:
                    if college.name.lower() in q_lower or college.slug.replace('-', ' ') in q_lower:
                        related_college = college
                        break

                new_qa_pairs.append(KnowledgeBaseQA(
                    question=q,
                    answer=a,
                    related_college=related_college,
                    is_verified=True
                ))
            
            # Bulk update or create replacement (simplified as delete + bulk_create for massive datasets if needed, 
            # but for now we'll stick to a more efficient loop or simple batching)
            # Actually, update_or_create in a loop is okay if the list is pre-loaded,
            # but KnowledgeBaseQA.objects.bulk_create is better for 1000s of items.
            
            KnowledgeBaseQA.objects.all().delete() # Refresh QA pairs
            KnowledgeBaseQA.objects.bulk_create(new_qa_pairs, batch_size=500)
            self.stdout.write(f'  - Synced {len(new_qa_pairs)} QA pairs via bulk update.')
        else:
            self.stdout.write(self.style.WARNING('training_data.json not found. Skipping QA sync.'))
